/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Owner' at '1/5/16 11:22 PM' with Gradle 2.10
 *
 * @author Owner, @date 1/5/16 11:22 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
