/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Owner' at '1/5/16 11:22 PM' with Gradle 2.10
 *
 * @author Owner, @date 1/5/16 11:22 PM
 */

import spock.lang.Specification

import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

class LibraryTest extends Specification{

    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }

    def "first crack at poi - write xlsx file"(){

        setup:
        Library lib = new Library()
        when:
        def result = lib.createXlsxFile()

        then:

        result == true

    }

    def "next crack at poi - write xlsx with ExcelHelper"(){

        setup:
        Library lib = new Library()
        when:
        def result = lib.createXlsxFile_01()

        then:

        result == true
    }

}
