/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Owner' at '1/5/16 11:22 PM' with Gradle 2.10
 *
 * @author Owner, @date 1/5/16 11:22 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
